OrderFood/Areas/Admin/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OrderFood.Models;
using OrderFood.Repository;
using X.PagedList;

namespace OrderFood.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FoodController : Controller
    {
        private IDishRepository _dishRepository;
        private ICategoryRepository _categoryRepository;
        public FoodController(IDishRepository dishRepository, ICategoryRepository categoryRepository)
        {
            _dishRepository = dishRepository;
            _categoryRepository = categoryRepository;
        }
        public IActionResult findDishCategory(int? id, string searchString, int page = 1, int pageSize = 10)
        {
            var categories = _categoryRepository.GetAll();
            ViewBag.Categories = categories;

            List<Dish> dishes;
            if (id.HasValue)
            {
                if (id.Value == 0) // check if the "Tất cả" option is selected
                {
                    dishes = _dishRepository.GetAll();
                }
                else
                {
                    dishes = _dishRepository.GetAllDishByCategoryID(id.Value);
                }

                ViewBag.CategoryId = id.Value; // set the CategoryId ViewBag variable
            }
            else
            {
                dishes = _dishRepository.GetAll();
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                dishes = _dishRepository.SearchDish(searchString);
                ViewBag.SearchString = searchString; // set the SearchString ViewBag variable
            }

            int totalItem = dishes.Count;
            int totalPages = (int)Math.Ceiling((double)totalItem / pageSize);

            dishes = dishes
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItem = totalItem;
            ViewBag.TotalPages = totalPages;

            return View("Index", dishes);
        }
        public IActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            List<Dish> dishes;
            if (!string.IsNullOrEmpty(searchString))
            {
                dishes = _dishRepository.SearchDish(searchString);
            }
            else
            {
                dishes = _dishRepository.GetAll();
            }

            int totalItem = dishes.Count;
            int totalPages = (int)Math.Ceiling((double)totalItem / pageSize);

            dishes = dishes
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            ViewBag.SearchString = searchString;
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItem = totalItem;
            ViewBag.TotalPages = totalPages;


            return View(dishes);
        }
        //Tạo
        [HttpPost]

        public IActionResult saveFood(Dish dish)
        {
            if (ModelState.IsValid)
            {

                _dishRepository.Create(dish);
                return RedirectToAction("Index");
            }
            else
            {
                var categories = _categoryRepository.GetAll()
                    .Select(c => new SelectListItem()
                    {
                        Text = c.NameCategory,
                        Value = c.CategoryId.ToString()
                    })
               .ToList();
                ViewBag.CategoryId = categories;
                return View("CreateFood", dish);
            }

        }
        public IActionResult CreateFood()
        {
            var categories = _categoryRepository.GetAll()
                     .Select(c => new SelectListItem()
                     {
                         Text = c.NameCategory,
                         Value = c.CategoryId.ToString()
                     })
                .ToList();
            ViewBag.CategoryId = categories;
            return View("CreateFood", new Dish());
        }
        //Xóa
        public IActionResult DeleteDish(string id)
        {
            _dishRepository.Delete(id);
            return RedirectToAction("Index");
        }
        //Chỉnh sửa
        [HttpPost]
        public IActionResult UpdateFood(Dish dish, IFormFile image)
        {
            if (image != null && image.Length > 0)
            {
                // Lưu hình ảnh mới vào thư mục và cập nhật thuộc tính Image của đối tượng Dish
                var imagePath = Path.Combine("wwwroot/images", image.FileName);
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    image.CopyTo(stream);
                }
                dish.Image = image.FileName;
            }
            else
            {
                // Giữ nguyên giá trị hiện tại của thuộc tính Image trong đối tượng Dish
                Dish currentDish = _dishRepository.findById(dish.DishId);
                dish.Image = currentDish.Image;
            }

            _dishRepository.Update(dish);
            return RedirectToAction("Index");
        }
        public IActionResult EditFood(string id)
        {
            var q1 = from c in _categoryRepository.GetAll()
                     select new SelectListItem()
                     {
                         Text = c.NameCategory,
                         Value = c.CategoryId.ToString()
                     };
            ViewBag.CategoryId = q1.ToList();
            return View("EditFood", _dishRepository.findById(id));
        }
        //Đếm món ăn đang có

    }
}

OrderFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace OrderFood.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OrderFood/Controllers/CartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrderFood.Areas.Identity.Data;
using OrderFood.Models;
using OrderFood.Repository;
using System.Data;
using System.Text.Json;

namespace OrderFood.Controllers
{
    public class CartController : Controller
    {
        private readonly SignInManager<AccountUser> _signInManager;
        private IDishRepository _dishRepository;
        private IOrderRepository _orderRepository;
        private IOrderItemRepository _orderItemRepository;
        private readonly OrderFoodDBContext _context;
        public CartController(OrderFoodDBContext dbContext, IDishRepository dishRepository, IOrderItemRepository orderItemRepository, IOrderRepository orderRepository, SignInManager<AccountUser> signInManager)
        {
            _signInManager = signInManager;
            _orderRepository = orderRepository;
            _dishRepository = dishRepository;
            _orderItemRepository = orderItemRepository;
            _context = dbContext;
        }
        public IActionResult Index()
        {
            ViewBag.sessionId = HttpContext.Session.Id;
            CartModel cartModel = new CartModel();
            cartModel.CartId = HttpContext.Session.Id;
            if (HttpContext.Session.GetString("cart") != null)
            {
                List<CarttItem> items = JsonSerializer.Deserialize<List<CarttItem>>(HttpContext.Session.GetString("cart"));
                cartModel.setAllItems(items);
            }
            return View(cartModel);
        }
        public IActionResult checkout()
        {
            CartModel cartModel = null;
            if (HttpContext.Session.GetString("cart") != null)
            {
                cartModel = new CartModel();
                cartModel.CartId = HttpContext.Session.Id;
                List<CarttItem> items = JsonSerializer.Deserialize<List<CarttItem>>(HttpContext.Session.GetString("cart"));
                cartModel.setAllItems(items);
            }
            ViewBag.CartModel = cartModel;
            return View(cartModel);
        }
        [HttpPost]
        public IActionResult PlaceOrder(Order order)
        {

            // Lấy tổng số tiền của đơn hàng
            CartModel cartModel = null;
            if (HttpContext.Session.GetString("cart") != null)
            {
                cartModel = new CartModel();
                cartModel.CartId = HttpContext.Session.Id;
                List<CarttItem> items = JsonSerializer.Deserialize<List<CarttItem>>(HttpContext.Session.GetString("cart"));
                cartModel.setAllItems(items);
            }

            // Lưu đơn hàng vào cơ sở dữ liệu
            var orderRepository = new OrderRepository(_context);
            orderRepository.AddOrder(order);

            // Lưu các mặt hàng vào bảng OrderItem
            if (cartModel != null && cartModel.getAllItems().Count > 0)
            {
                List<CarttItem> cartItems = cartModel.getAllItems();
                string NameDish = string.Join(",", cartItems.Select(item => item.Name));

                var orderItem = new OrderItem
                {
                    OrderId = order.OrderId,
                    NameDish = NameDish,
                    OrderDate = DateTime.Now,
                    Quantity = cartItems.Sum(c => c.Quantity),
                    Status = "Chưa xác nhận",
                    Total = (float)cartItems.Sum(c => c.Quantity * c.Price)
                };

                var orderItemRepository = new OrderItemRepository(_context);
                orderItemRepository.AddOrderItems(orderItem);
            }

            // Xóa giỏ hàng khỏi phiên làm việc
            HttpContext.Session.Remove("cart");

            // Chuyển hướng đến trang cảm ơn
            return RedirectToAction("Index", "Menu");
        }

        public IActionResult AddToCart(string id)
        {
            // Tìm mặt hàng theo id
            Dish dish = _dishRepository.findByDishId(id);
            int quantity = 1;
            CartModel cartModel = null;
            if (HttpContext.Session.GetString("cart") != null)
            {
                // Bước 1: Lấy giỏ hàng từ phiên làm việc
                cartModel = new CartModel();
                cartModel.CartId = HttpContext.Session.Id;

                // Đọc dữ liệu phiên biểu mẫu vào giỏ hàng
                List<CarttItem> items = JsonSerializer.Deserialize<List<CarttItem>>(HttpContext.Session.GetString("cart"));
                cartModel.setAllItems(items);

                // Thêm mặt hàng mới vào giỏ hàng
                CarttItem cartItem = new CarttItem()
                {
                    Id = dish.DishId,
                    Name = dish.NameDish,
                    Price = dish.Price,
                    ImagePath = dish.Image,
                    Quantity = quantity,
                    LineTotal = quantity * dish.Price
                };
                cartModel.addCartItem(cartItem);
                HttpContext.Session.SetString("cart", JsonSerializer.Serialize(cartModel.getAllItems()));
            }
            else
            {
                // Tạo giỏ hàng mới nếu chưa có
                cartModel = new CartModel();
                cartModel.CartId = HttpContext.Session.Id;
                CarttItem item = new CarttItem()
                {
                    Id = dish.DishId,
                    Name = dish.NameDish,
                    Price = dish.Price,
                    ImagePath = dish.Image,
                    Quantity = quantity,
                    LineTotal = quantity * dish.Price
                };
                cartModel.addCartItem(item);
                HttpContext.Session.SetString("cart", JsonSerializer.Serialize(cartModel.getAllItems()));
            }
            return RedirectToAction("Index", "Menu");
        }


        public IActionResult UpdateQuantity()
        {
            var btn = Request.Form["btnUpdateQuantity"].ToString();
            var id = Request.Form["item.id"].ToString();
            var qty = int.Parse(Request.Form["item.Quantity"]);

            CartModel cartModel = null;
            if (HttpContext.Session.Get("cart") != null)
            {
                cartModel = new CartModel();
                cartModel.CartId = HttpContext.Session.Id;
                string cartJson = HttpContext.Session.GetString("cart");
                List<CarttItem> cartItems = JsonSerializer.Deserialize<List<CarttItem>>(cartJson);
                cartModel.setAllItems(cartItems);

            }
            cartModel.UpdateQuantity(id, 1, btn);

            HttpContext.Session.SetString("cart", JsonSerializer.Serialize(cartModel.getAllItems()));
            return RedirectToAction("Index");
        }
        public IActionResult RemoveFromCart(string id)
        {
            CartModel cartModel = null;
            if (HttpContext.Session.GetString("cart") != null)
            {
                cartModel = new CartModel();
                cartModel.CartId = HttpContext.Session.Id;
                List<CarttItem> items = JsonSerializer.Deserialize<List<CarttItem>>(HttpContext.Session.GetString("cart"));
                cartModel.setAllItems(items);
                cartModel.RemoveCartItem(id);
                HttpContext.Session.SetString("cart", JsonSerializer.Serialize(cartModel.getAllItems()));
            }
            return RedirectToAction("Index");
        }

    }
}

OrderFood/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OrderFood.Areas.Identity.Data;
using OrderFood.Repository;

namespace OrderFood.Controllers
{
    public class ProfileController : Controller
    {
        private readonly SignInManager<AccountUser> _signInManager;
        private readonly UserManager<AccountUser> _userManager;
        private readonly IAccountRepository _accountRepository;
        private readonly IOrderRepository _orderRepository;
        private readonly IOrderItemRepository _orderItemRepository;
        public ProfileController(SignInManager<AccountUser> signInManager,
            UserManager<AccountUser> userManager,
            IAccountRepository accountRepository,
            IOrderRepository orderRepository,
            IOrderItemRepository orderItemRepository)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _accountRepository = accountRepository;
            _orderRepository = orderRepository;
            _orderItemRepository = orderItemRepository;
        }
        public async Task<IActionResult> Index()
        {
            //lấy thông tin đang đăng nhập
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                //ko tìm thấy chuyển đến trang đăng nhập
                return RedirectToAction("Login", "Account");
            }
            //truyền thông tin tài khoản vào view
            return View(user);
        }

        //public IActionResult EditProfile(string id)
        //{
        //    var account = _accountRepository.findbyId(id);
        //    return View(account);
        //}
        [HttpPost]
        public IActionResult UpdateProfile(AccountUser accountUser)
        {
            _accountRepository.UpdateAccount(accountUser);
            return RedirectToAction("Index");
        }

        public IActionResult MyOrder()
        {
            var userId = Guid.Parse(_userManager.GetUserId(User));

            // Lấy danh sách Order của người dùng hiện tại
            var orders = _orderRepository.GetOrderByUserId(userId)
                .OrderByDescending(o => o.PaymentMethods)
                .ToList();

            foreach (var order in orders)
            {
                // Lấy danh sách OrderItem của từng Order
                var orderItems = _orderItemRepository.GetOrderItemsByOrderId(order.OrderId)
                    .OrderByDescending(oi => oi.OrderDate)
                    .ToList();
                order.OrderItems = orderItems;
            }

            return View(orders);
        }
    }
}

OrderFood/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using OrderFood.Areas.Identity.Data

@inject SignInManager<AccountUser> SignInManager
@inject UserManager<AccountUser> UserManager
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="images/favicon.png" type="">

    <title> Fast Food </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <!-- nice select  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
    <!-- font awesome style -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css-cart/cart.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
    <link href="~/css-checkout/checkout.css" rel="stylesheet" />
    <link href="~/css-dishdetail/DishDetail.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/css/responsive.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>

    <div class="hero_area">

        <!-- header section strats -->
        <header class="header_section" style="background-color:black;">
            <div class="container">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <span>
                            Fast Food
                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav  mx-auto ">
                            <li class="nav-item active">
                                <a class="nav-link active " asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Menu" asp-action="Index">Thực đơn</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="About" asp-action="Index">Về FastFood</a>

                               
                            </li>

                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="Admin" asp-controller="Home" asp-action="Index">Quản Lý</a>
                                </li>
                            }
                            <li class="nav-item">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @UserManager.GetUserName(User)!
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-action="Index" asp-controller="Profile">Thông tin cá nhân</a>
                                        <a class="dropdown-item" asp-action="MyOrder" asp-controller="Profile">Đơn hàng đã đặt</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="/home/logout">Đăng xuất</a>
                                    </div>
                                </li>
                                }
                                else
                                {
                                <li class="nav-item"><a href="Identity/Account/Login?ReturnUrl=%2F" class="nav-link "> Đăng nhập</a></li>
                                <li class="nav-item"><a href="/Identity/Account/Register" class="nav-link "> Đăng ký</a></li>
                                }
                            </li>
                        </ul>

                        <div class="user_option">

                            <a class="cart_link" asp-area="" asp-controller="Cart" asp-action="Index">
                                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                                <g>
                                <g>
                                <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                    </g>
                  </g>
                                <g>
                                <g>
                                <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                   C457.728,97.71,450.56,86.958,439.296,84.91z" />
                    </g>
                  </g>
                                <g>
                                <g>
                                <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                    </g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                                <g>
                  </g>
                </svg>
                            </a>


                        </div>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
        <!-- slider section -->
        @RenderBody()

        <!-- end client section -->
        <!-- footer section -->
        <footer class="footer_section">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-col">
                        <div class="footer_contact">
                            <h4> Liên hệ </h4>
                            <div class="contact_link_box"> <a href=""> <i class="fa fa-map-marker" aria-hidden="true"></i> 
                                <span> Địa chỉ </span> </a> <a href=""> 
                                    <i class="fa fa-envelope" aria-hidden="true"></i> 
                                        <span> truongtanhung1910@gmail.com </span> </a> </div>
                        </div>
                    </div>
                    <div class="col-md-4 footer-col">
                        <div class="footer_detail">
                            <a href="" class="footer-logo"> Fast Food </a> 
                           
                            <div class="footer_social">
                                <a href=""> <i class="fa fa-facebook" aria-hidden="true"></i> </a>
                                <a href=""> <i class="fa fa-twitter" aria-hidden="true"></i> </a> <a href=""> <i class="fa fa-linkedin" aria-hidden="true"></i> </a>
                                <a href=""> <i class="fa fa-instagram" aria-hidden="true"></i> </a> <a href=""> <i class="fa fa-pinterest" aria-hidden="true"></i> </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 footer-col"> <h4> Giờ mở cửa </h4> <p> Mỗi ngày </p> <p> 10.00 Sáng - 10.00 Tối </p> </div>
                </div>
               
            </div>
        </footer>
        <!-- footer section -->
        <!-- jQery -->
        <script src="~/js/jquery-3.4.1.min.js"></script>
       
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <!-- popper js -->
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
        </script>
        <!-- bootstrap js -->
        <script src="~/js/bootstrap.js"></script>
        <!-- owl slider -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
        </script>
        <!-- isotope js -->
        <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
        <!-- nice select -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
        <!-- custom js -->
        <script src="~/js/custom.js"></script>
        <!-- Google Map -->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
        </script>
        <!-- End Google Map -->
        
</body>

</html>